In [2]:
aList  = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [3]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
bin_colors[1]

'Green'

In [4]:
bin_colors[0:2]

['Red', 'Green']

In [5]:
bin_colors[2:]

['Blue', 'Yellow']

In [6]:
bin_colors[:2]

['Red', 'Green']

In [7]:
bin_colors[:-1]

['Red', 'Green', 'Blue']

In [8]:
bin_colors[:-2]

['Red', 'Green']

In [9]:
a = [1,2,[100,200,300],6]
max(a[2])

300

In [10]:
a[2][1]

200

In [11]:
for aColor in bin_colors:
    print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [13]:
list(filter(lambda x: x > 100, [-5, 200, 300, -10, 10, 1000]))

[200, 300, 1000]

In [14]:
list(map(lambda x: x ** 2, [11, 22, 33, 44, 55]))

[121, 484, 1089, 1936, 3025]

In [16]:
from functools import reduce

def doSum(x1, x2):
    return x1+x2

x = reduce(doSum, [100, 122, 33, 4, 5, 6])
x

270

In [18]:
x = range(6)
list(x)

[0, 1, 2, 3, 4, 5]

In [19]:
oddNum = range(3, 29, 2)
list(oddNum)

[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27]

In [1]:
bin_colors = ('Red', 'Green', "Blue", "Yellow")
bin_colors[1]

'Green'

In [2]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [3]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [4]:
yellow = {'dandelions', 'fire_hydrant', 'leaves'}
red = {'fire_hydrantf', 'blood', 'rose', 'leaves'}

In [5]:
yellow|red

{'blood', 'dandelions', 'fire_hydrant', 'fire_hydrantf', 'leaves', 'rose'}

In [6]:
yellow&red

{'leaves'}

In [9]:
import pandas as pd

df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]
])
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [10]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [12]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [13]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [14]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [15]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [20]:
import numpy as np

myMatrix = np.array([[11,12,23], [21,22,23], [31,32,33]])
print(myMatrix)
print(type(myMatrix))

[[11 12 23]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [21]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [23, 23, 33]])

In [22]:
myVector = [22,33,44,55]
print(myVector)
print(type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [23]:
myVector = np.array([22,33,44,55])
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [27]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [28]:
stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [29]:
stack.pop()

'Yellow'

In [30]:
stack.isEmpty()

False

In [31]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [33]:
queue = Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')

In [34]:
print(queue.size())

4


In [35]:
print(queue.dequeue())

Red


In [36]:
print(queue.dequeue())

Green
